/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */
plugins {
//    id("gradlebuild.wrapper")
//    id("gradlebuild.quick-check")
}

tasks.register("test1") {
    println("test1")
}

tasks.register("test2") {
    println("test2")
}

tasks.getByName("test1").dependsOn("test2")